import "./globals.css";
import { Inter } from "next/font/google";
import c from "classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={c("bg-gray-100", inter.className)}>
        <div className="border-b bg-white">
          <div className="container mx-auto max-w-screen-lg ">
            <header className="flex justify-between items-center py-2 text-gray-600 font-medium px-4">
              <div>logo</div>
              <nav className="flex space-x-4 items-center">
                <a href="#">Add</a>
                <a href="#">Decks</a>
                <a
                  href="#"
                  className="bg-black text-white rounded-full px-4 py-2 relative"
                >
                  Quiz
                </a>
                <a href="#">
                  <BellIcon />
                </a>
                <a href="#" className="rounded-full w-10 h-10 bg-blue-400"></a>
              </nav>
            </header>
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}

const BellIcon = () => {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      strokeWidth={1.5}
      stroke="currentColor"
      className="w-6 h-6"
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0"
      />
    </svg>
  );
};
